# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hackshackers 2017"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "https://hackshackers.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = "Hacks/Hackers"
  homepage = "https://hackshackers.com/"
